version: '3'

services:
  app:
    build: .
    entrypoint: wait-for db:3306 -t 40 -- ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on: 
      - db
    networks:
      - kafka_kafka-net

  db:
    build: ./.docker/mysql
    restart: always
    tty: true
    networks:
      - kafka_kafka-net
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fin
      - MYSQL_ROOT_PASSWORD=root

networks:
  kafka_kafka-net:
    external: true