version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - kafka-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka-0:
    image: confluentinc/cp-kafka:5.4.1
    container_name: kafka-0
    ports:
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:29094,PLAINTEXT_HOST://localhost:9093
      # If you don't specify KAFKA_LISTENERS it will default to the ports used in
      # KAFKA_ADVERTISED_LISTENERS, but IMO it's better to be explicit about these settings
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29094,PLAINTEXT_HOST://0.0.0.0:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  kafka-topics-generator:
    image: confluentinc/cp-kafka:5.4.1
    depends_on:
      - kafka-0
    networks:
      - kafka-net
    command: >
      bash -c
        "sleep 5s &&
        kafka-topics --create --topic=transactions --if-not-exists --bootstrap-server=kafka-0:29094 && 
        kafka-topics --create --topic=transactions_result --if-not-exists --bootstrap-server=kafka-0:29094"
        
  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.1
    hostname: control-center
    depends_on:
      - kafka-0
    ports:
      - "9021:9021"
    networks:
      - kafka-net
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka-0:29094'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      PORT: 9021

networks:
  kafka-net:
    driver: bridge