version: '3'

services:
  app:
    container_name: nextjs
    env_file:
      - .env
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/home/node/app
    networks:
      - kafka_kafka-net

networks:
  kafka_kafka-net:
    external: true